from dotenv import load_dotenv
import os
import sys

# Load env vars
load_dotenv()

from src.supervisor import SupervisorAgent
from src.state import ResearchStage
from src.agents.verifier import VerifierAgent # <--- NEW IMPORT

def main():
    # 1. API Check
    if not os.getenv("SERPAPI_KEY") or not os.getenv("GOOGLE_API_KEY"):
        print("\n[!] CRITICAL: Keys missing in .env file.")
        return

    print("\n--- 🕵️  MicroSaaS Idea Validator (Agent Swarm) ---")

    # 2. Guided Input (The Update)
    print("\n[TIP] For best results, use the formula: '[Specific Process] software for [Specific Industry]'")
    print("      Example: 'HACCP audit compliance software for commercial kitchens'")
    
    # 2. Raw Input
    raw_niche = input("\n>> Enter Niche Idea: ")
    country_input = input(">> Enter Country Code (default 'in'): ") or "in"

    # 3. INTENT VERIFICATION LOOP (The New Quality Gate)
    verifier = VerifierAgent()
    final_niche = raw_niche
    
    while True:
        feedback = verifier.verify_niche(final_niche)
        
        if feedback.get("status") == "valid":
            print(f"\n✅ Prompt Verified: Excellent specificity.")
            break
        
        # If vague, show options
        print(f"\n⚠️  Critique: {feedback.get('critique')}")
        print("   Better options generated by AI:")
        
        suggestions = feedback.get("suggestions", [])
        for i, opt in enumerate(suggestions):
            print(f"   [{i+1}] {opt}")
        
        print(f"   [0] Keep my original: '{final_niche}'")
        
        choice = input("\n>> Pick a number (1-3) or 0 to proceed: ")
        
        if choice == '0':
            print("   -> Proceeding with original input.")
            break
        elif choice.isdigit() and 1 <= int(choice) <= len(suggestions):
            final_niche = suggestions[int(choice)-1]
            print(f"   -> Switched to: '{final_niche}'")
            break
        else:
            print("   -> Invalid choice. Trying again...")

    # 4. Launch Supervisor with the OPTIMIZED Niche
    print(f"\n🚀 Launching Supervisor for: '{final_niche}'...")
    supervisor = SupervisorAgent(niche=final_niche, country_code=country_input)
    
    # 5. Run Workflow
    state = supervisor.run()

    # 6. Checkpoint Handling
    if state.current_stage == ResearchStage.HUNTING_REVIEW:
        print("\n------------------------------------------------")
        user_decision = input(">> Supervisor needs approval. Type 'ok' to proceed: ")
        
        if user_decision.lower() == 'ok':
            print(">> Approval received. Resuming workflow...")
            state.current_stage = ResearchStage.MINING
            supervisor.run()
        else:
            print(">> Workflow halted.")

if __name__ == "__main__":
    main()