import os
import time
from .state import ResearchState

class ReportGenerator:
    def __init__(self, output_dir="reports"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

    def save_report(self, state: ResearchState) -> str:
        filename = f"{self.output_dir}/product_discovery_{state.project_id}.md"
        content = self._build_markdown(state)
        
        with open(filename, "w", encoding="utf-8") as f:
            f.write(content)
            
        print(f"   [Report] Saved detailed report to {filename}")
        return filename

    def _build_markdown(self, state: ResearchState) -> str:
        md = []
                for g in spec.prd.goals:
                    md.append(f"- {g}")
                    
                md.append("\n#### ⛔ Non-Goals")
                for ng in spec.prd.non_goals:
                    md.append(f"- {ng}")
                    
                md.append("\n#### 🛤️ Core User Flow")
                for idx, step in enumerate(spec.prd.user_flow):
                    md.append(f"{idx+1}. {step}")
                    
                md.append("\n#### 🚩 Risks & Unknowns")
                for r in spec.prd.risks_and_unknowns:
                    md.append(f"- {r}")

                md.append("\n#### ✨ MVP Feature Specification")
                md.append("| Feature | Description | Success Metric |")
                md.append("| :--- | :--- | :--- |")
                for f in spec.prd.mvp_features:
                    md.append(f"| {f.name} | {f.description} | {f.success_metric} |")

        if spec.feature_roadmap:
             md.append("\n### 🗺️ Strategic Roadmap Rationale")
             md.append("| Priority | Feature | Solves Cluster | Justification (Failure of Current Solutions) |")
             md.append("| :--- | :--- | :--- | :--- |")
             for f in spec.feature_roadmap:
                prio = "MVP" if f.mvp_priority else "Phase 2"
                md.append(f"| {prio} | {f.proposed_feature} | {f.pain_theme} | {f.current_failure} |")
        
        md.append("\n## 6. Deep Dive Clusters (Synthesized)")
        if state.pain_clusters:
            for c in state.pain_clusters:
                md.append(f"### {c.cluster_name} ({c.severity})")
                md.append(f"**Real Problem:** {c.description}")
                md.append(f"**Why Angry:** {c.why_users_get_angry}")
                md.append(f"**Personas:** {', '.join(c.affected_personas)}")
                md.append(f"**Impact:** Trial: {c.impact_summary.trial_blocker} | Conversion: {c.impact_summary.conversion_blocker}")
                md.append("**Quotes:**")
                for q in c.representative_quotes:
                    md.append(f"> {q}")
                md.append("\n")

        md.append("\n---\n*Generated by MicroSaaS Agent Swarm*")
        return "\n".join(md)
        if state.final_ideas:
            md.append("| Target Keyword | Vol (Est.) | Score | Idea |")
            md.append("| :--- | :--- | :--- | :--- |")
            for idea in state.final_ideas:
                md.append(f"| `{idea.target_keyword}` | {idea.search_volume} | **{idea.opportunity_score}** | {idea.description} |")
        else:
            md.append("*No validated ideas generated.*")
            
        md.append("\n---\n*Generated by MicroSaaS Agent Swarm*")
        return "\n".join(md)