import os
import time
from .state import ResearchState

class ReportGenerator:
    def __init__(self, output_dir="reports"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

    def save_report(self, state: ResearchState) -> str:
        """Generates a Markdown report and saves it. Returns the filename."""
        
        # 1. Build the Content
        content = self._build_markdown(state)
        
        # 2. Generate Filename (Sanitized)
        safe_niche = "".join(c for c in state.niche if c.isalnum() or c in (' ', '_')).rstrip()
        safe_niche = safe_niche.replace(" ", "_").lower()
        timestamp = time.strftime("%Y%m%d-%H%M")
        filename = f"{self.output_dir}/{timestamp}_{safe_niche}.md"
        
        # 3. Write File
        with open(filename, "w", encoding="utf-8") as f:
            f.write(content)
            
        return filename

    def _build_markdown(self, state: ResearchState) -> str:
        md = []
        md.append(f"# 🕵️ MicroSaaS Validation Report: {state.niche}")
        md.append(f"**Date:** {time.strftime('%Y-%m-%d %H:%M')} | **Region:** {state.country_code.upper()}\n")
        
        md.append("## 1. Executive Summary")
        top_idea = state.final_ideas[0] if state.final_ideas else None
        if top_idea:
            md.append(f"**Top Opportunity:** {top_idea.description}")
            md.append(f"**Potential:** {top_idea.opportunity_score}/10")
        else:
            md.append("No high-confidence opportunities found.")
        md.append("---\n")

        md.append("## 2. Market Landscape (Competitors)")
        if state.competitors:
            for comp in state.competitors:
                status = "✅ Relevant" if comp.is_relevant else "❌ Ignored"
                md.append(f"- **{comp.name}**: {status}")
                if comp.url: md.append(f"  - {comp.url}")
        else:
            md.append("*No competitors analyzed.*")
        md.append("\n")

        md.append("## 3. The Pain (Voice of Customer)")
        if state.pain_points:
            md.append("| Category | Quote | Frequency |")
            md.append("| :--- | :--- | :--- |")
            for p in state.pain_points[:10]: # Top 10 only
                quote = p.quote.replace('\n', ' ').strip()[:100] + "..."
                md.append(f"| {p.pain_category} | \"{quote}\" | {p.frequency} |")
        else:
            md.append("*No significant pain points extracted.*")
        md.append("\n")

        md.append("## 4. Validated Opportunities")
        if state.product_spec:
            spec = state.product_spec
            md.append("\n## 5. 🏗️ The Architect's Blueprint (MVP Spec)")
            md.append(f"### **Project Name:** {spec.mvp_name}")
            md.append(f"> *{spec.tagline}*")
            
            md.append("\n**marketing Hook (Hero Text):**")
            md.append(f"`{spec.marketing_hook}`")
            
            md.append("\n**Core Features (MVP):**")
            for feat in spec.core_features:
                md.append(f"- [ ] {feat}")
                
            md.append("\n**Recommended Stack:**")
            md.append(f"`{' | '.join(spec.tech_stack_recommendation)}`")
            
            md.append("\n**User Stories:**")
            for story in spec.user_stories:
                md.append(f"- {story}")
        # -----------------------------------------------

        md.append("\n---\n*Generated by MicroSaaS Agent Swarm*")
        return "\n".join(md)
        if state.final_ideas:
            md.append("| Target Keyword | Vol (Est.) | Score | Idea |")
            md.append("| :--- | :--- | :--- | :--- |")
            for idea in state.final_ideas:
                md.append(f"| `{idea.target_keyword}` | {idea.search_volume} | **{idea.opportunity_score}** | {idea.description} |")
        else:
            md.append("*No validated ideas generated.*")
            
        md.append("\n---\n*Generated by MicroSaaS Agent Swarm*")
        return "\n".join(md)